# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BS <- function(t, knots, constantVE) {
    .Call('_DOVE_BS', PACKAGE = 'DOVE', t, knots, constantVE)
}

Cox <- function(beta, gamma, time, delta, X, W, S, knots, constantVE, threshold = 10^(-4), maxit = 500L) {
    .Call('_DOVE_Cox', PACKAGE = 'DOVE', beta, gamma, time, delta, X, W, S, knots, constantVE, threshold, maxit)
}

Cox_noX <- function(gamma, time, delta, W, S, knots, constantVE, threshold = 10^(-4), maxit = 500L) {
    .Call('_DOVE_Cox_noX', PACKAGE = 'DOVE', gamma, time, delta, W, S, knots, constantVE, threshold, maxit)
}

iteration <- function(dt, DZBBy, X, indVac, loc, score2Prep, m, vac) {
    .Call('_DOVE_iteration', PACKAGE = 'DOVE', dt, DZBBy, X, indVac, loc, score2Prep, m, vac)
}

iteration_NoX <- function(dt, DZBBy, indVac, loc, score2Prep, m) {
    .Call('_DOVE_iteration_NoX', PACKAGE = 'DOVE', dt, DZBBy, indVac, loc, score2Prep, m)
}

